[tool.poetry]
name = "lecture-ai-engineering"
version = "0.1.0"
description = ""
authors = ["Ryota Kobayashi <s.woods.m.29@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
dotenv = "^0.9.9"
huggingface-hub = {extras = ["cli"], version = "^0.30.2"}
pandas-stubs = "^2.2.3.250308"
torch = {version = "^2.7.0+cu118", source = "pytorch-cu118"}
torchvision = {version = "^0.22.0+cu118", source = "pytorch-cu118"}


[tool.poetry.group.dev.dependencies]
ipykernel = "^6.29.5"


[[tool.poetry.source]]
name = "pytorch-cu118"
url = "https://download.pytorch.org/whl/cu118"
priority = "explicit"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
